name: build

on:
  workflow_call:

jobs:
  compute-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get_tag.outputs.TAGS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - if: ${{ github.event_name == 'push' }}
        name: Get the latest tag
        id: get_tag
        run: |
          {
            echo 'TAGS<<EOF'
            echo "${{ github.sha }}"
            echo "${{ github.ref_name}}"
            echo EOF
          } >> "$GITHUB_OUTPUT"

  build-keda-manager:
    needs: compute-tags
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: keda-manager
      dockerfile: Dockerfile
      tags: ${{ needs.compute-tags.outputs.tags }}
