name: integration tests

on:
  workflow_call:
    inputs:
      image:
        description: 'The image to test'
        required: true
        type: string

jobs:
  integration-test:
    if: ${{ !startsWith(github.event_name, 'pull_request') || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: ./.github/actions/setup-go
      - uses: ./.github/actions/create-k3d-cluster
      - name: run test
        run: make -C hack/ci integration-test-on-cluster
        env:
          IMG: ${{ inputs.image }}

  btp-integration-tests:
    if: ${{ !startsWith(github.event_name, 'pull_request') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test/btp/hack
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-kyma
        with:
          path: "test/btp/bin"
      - name: Create btp account with kyma enable
        run: |
          . ./set-tf-envs.sh
          terraform -chdir=../tf init
          terraform -chdir=../tf apply -auto-approve
          echo "SUBACC_ID=$(terraform -chdir=../tf output -raw subaccount_id)" >> $GITHUB_ENV
        env:
          BTP_ENV: ${{ secrets.BTP_INTEGRATION_TEST }}
          TF_VAR_BTP_NEW_SUBACCOUNT_NAME: keda-registry-test-${{ github.sha }}-${{ github.run_attempt }}
          