name: push

on:
  push:
    branches: [ "main", "release-*" ]

jobs:
  builds:
    uses: ./.github/workflows/_build.yaml

  upgrades:
    needs: builds
    uses: ./.github/workflows/_upgrade-tests.yaml

  integrations:
    needs: builds
    uses: ./.github/workflows/_integration-tests.yaml
    with:
      image: europe-docker.pkg.dev/kyma-project/dev/keda-manager:PR-${{ github.sha }}