name: push

on:
  push:
    branches: [ "main", "release-*" ]

jobs:
  integrations:
    needs: builds
    uses: ./.github/workflows/_integration-tests.yaml
    with:
      image: europe-docker.pkg.dev/kyma-project/dev/keda-manager:PR-515