# Call this workflow from other jobs to execute unit tests in the current context

name: Run module tests on the cluster

on:
  workflow_call:
    inputs:
      image-repo:
        description: Binary image registry reference
        required: true
        type: string
      image-tag:
        description: Binary image tag
        required: true
        type: string
      skip-templates:
        description: wait for images only, skip template artifacts
        required: false
        type: string

jobs:
  run-e2e-tests:
    # job waits until Prow job uploads docker image, module OCI image and optionally artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare k3s cluster and docker registry
        run: "./scripts/k3s-setup.sh --wait"

      - name: Wait for artifacts
        env:
          KEDA_MANAGER_REPO: ${{ inputs.image-repo }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "./scripts/await_artifacts.sh ${{ inputs.image-tag }}"

      - name: Run tests
        run: "./scripts/module_tests.sh ${{ inputs.image-tag }} ci"
